addons:
  apt:
    packages:
    - libtool
    - pkg-config
    - libcurl4-openssl-dev
    - libjson-c-dev

language: c

compiler:
  - gcc
  - clang

script: ./autogen.sh && ./configure && make && make check
